from django.db import models


class PriceCurrencyEnum(models.TextChoices):
    UAH = "uah", "UAH"
    USD = "usd", "USD"


class VolumeMl(models.TextChoices):
    ML_10 = "10", "10 ml"
    ML_20 = "20", "20 ml"
    ML_30 = "30", "30 ml"
    ML_50 = "50", "50 ml"
    ML_75 = "75", "75 ml"
    ML_100 = "100", "100 ml"


class FirstNote(models.TextChoices):
    BERGAMOT = "bergamot"
    LEMON = "lemon"
    LIME = "lime"
    GRAPEFRUIT = "grapefruit"
    MANDARIN = "mandarin"
    TANGERINE = "tangerine"
    ORANGE_SWEET = "sweet orange"
    ORANGE_BITTER = "bitter orange"
    POMELO = "pomelo"
    YUZU = "yuzu"
    KUMQUAT = "kumquat"
    CITRON = "citron"
    PETITGRAIN = "petitgrain"

    BLACKCURRANT_LEAF = "blackcurrant leaf"
    GREEN_LEAF = "green leaf"
    FRESH_GRASS = "fresh grass"
    CUCUMBER = "cucumber"
    TOMATO_LEAF = "tomato leaf"
    BAMBOO = "bamboo"
    SHISO = "shiso"
    VERBENA = "verbena"
    LEMONGRASS = "lemongrass"

    SEA_SALT = "sea salt"
    MARINE_BREEZE = "marine breeze"
    OZONE = "ozone"
    AQUATIC_NOTES = "aquatic notes"

    PEPPERMINT = "peppermint"
    MINT = "mint"
    BASIL = "basil"
    ROSEMARY = "rosemary"
    THYME = "thyme"
    TARRAGON = "tarragon"
    CLARY_SAGE = "clary sage"
    EUCALYPTUS = "eucalyptus"
    JUNIPER_BERRY = "juniper berry"

    GINGER = "ginger"
    PINK_PEPPER = "pink pepper"
    BLACK_PEPPER = "black pepper"
    CARDAMOM = "cardamom"
    CORIANDER = "coriander"
    ANISE = "anise"
    FENNEL = "fennel"

    GREEN_APPLE = "green apple"
    PEAR = "pear"
    PINEAPPLE = "pineapple"
    MELON = "melon"
    WATERMELON = "watermelon"
    LYCHEE = "lychee"
    WHITE_GRAPE = "white grape"
    KIWI = "kiwi"

    ALDEHYDES = "aldehydes"


class HeartNote(models.TextChoices):
    ROSE = "rose"
    JASMINE = "jasmine"
    ORANGE_BLOSSOM = "orange blossom"
    NEROLI = "neroli"
    PEONY = "peony"
    MAGNOLIA = "magnolia"
    LILY_OF_THE_VALLEY = "lily of the valley"
    FREESIA = "freesia"
    YLANG_YLANG = "ylang-ylang"
    TUBEROSE = "tuberose"
    GARDENIA = "gardenia"
    OSMANTHUS = "osmanthus"
    VIOLET = "violet"
    IRIS_FLOWER = "iris"
    LOTUS = "lotus"
    LILY = "lily"
    LAVENDER = "lavender"
    GERANIUM = "geranium"
    LILAC = "lilac"
    MIMOSA = "mimosa"
    HYACINTH = "hyacinth"

    PEACH = "peach"
    APRICOT = "apricot"
    PLUM = "plum"
    SOUR_CHERRY = "sour cherry"
    SWEET_CHERRY = "sweet cherry"
    RASPBERRY = "raspberry"
    STRAWBERRY = "strawberry"
    BLACKBERRY = "blackberry"
    BLUEBERRY = "blueberry"
    POMEGRANATE = "pomegranate"
    FIG = "fig"
    MANGO = "mango"
    PASSION_FRUIT = "passion fruit"
    COCONUT = "coconut"
    LYCHEE = "lychee"

    BLACK_TEA = "black tea"
    GREEN_TEA = "green tea"
    MATE = "mate"
    CHAMOMILE = "chamomile"

    CINNAMON = "cinnamon"
    CLOVE = "clove"
    NUTMEG = "nutmeg"
    CARAWAY = "caraway"
    CANDIED_GINGER = "candied ginger"

    HONEY = "honey"
    FLORAL_HONEY = "floral honey"
    POWDERY_NOTE = "powdery note"
    RHUBARB = "rhubarb"
    ELDERFLOWER = "elderflower"


class LastNote(models.TextChoices):
    CEDAR = "cedar"
    SANDALWOOD = "sandalwood"
    PATCHOULI = "patchouli"
    VETIVER = "vetiver"
    GUAIAC_WOOD = "guaiac wood"
    OUD = "oud"
    AGARWOOD = "agarwood"
    OAK = "oak"
    TEAK = "teak"
    ROSEWOOD = "rosewood"
    AMYRIS = "amyris"
    CASHMERAN = "cashmeran"
    ISO_E_SUPER = "Iso E Super"
    AMBERWOOD = "amberwood"

    LABDANUM = "labdanum"
    BENZOIN = "benzoin"
    OPOPONAX = "opoponax"
    MYRRH = "myrrh"
    FRANKINCENSE = "frankincense"
    PERU_BALSAM = "peru balsam"
    TOLU_BALSAM = "tolu balsam"
    AMBER = "amber"
    AMBROXAN = "ambroxan"
    AMBERGRIS = "ambergris"

    WHITE_MUSK = "white musk"
    MUSK = "musk"

    VANILLA = "vanilla"
    TONKA_BEAN = "tonka bean"
    COCOA = "cocoa"
    CHOCOLATE = "chocolate"
    COFFEE = "coffee"
    PRALINE = "praline"
    CARAMEL = "caramel"
    ORRIS_BUTTER = "orris butter"
    ORRIS_POWDER = "orris powder"
    MARSHMALLOW = "marshmallow"
    SUGAR = "sugar"
    TOFFEE = "toffee"

    TOBACCO = "tobacco"
    TOBACCO_LEAF = "tobacco leaf"
    OAKMOSS = "oakmoss"
    LEATHER = "leather"
    SUEDE = "suede"
    BIRCH_TAR = "birch tar"
    HAY = "hay"

    SMOKE = "smoke"
    RESINOUS_SMOKE = "resinous smoke"
    NUTTY_CHOCOLATE_ACCORD = "nutty chocolate accord"


class Sex(models.TextChoices):
    MALE = "male", "Male"
    FEMALE = "female", "Female"
    UNISEX = "unisex", "Unisex"
