# Generated by Django 5.2.7 on 2025-11-10 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('uah', 'UAH'), ('usd', 'USD')], max_length=10)),
                ('available', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('volume', models.CharField(choices=[('10', '10 ml'), ('20', '20 ml'), ('30', '30 ml'), ('50', '50 ml'), ('75', '75 ml'), ('100', '100 ml')], max_length=100)),
                ('description', models.TextField()),
                ('first_notes', models.CharField(choices=[('bergamot', 'Bergamot'), ('lemon', 'Lemon'), ('lime', 'Lime'), ('grapefruit', 'Grapefruit'), ('mandarin', 'Mandarin'), ('tangerine', 'Tangerine'), ('sweet orange', 'Orange Sweet'), ('bitter orange', 'Orange Bitter'), ('pomelo', 'Pomelo'), ('yuzu', 'Yuzu'), ('kumquat', 'Kumquat'), ('citron', 'Citron'), ('petitgrain', 'Petitgrain'), ('blackcurrant leaf', 'Blackcurrant Leaf'), ('green leaf', 'Green Leaf'), ('fresh grass', 'Fresh Grass'), ('cucumber', 'Cucumber'), ('tomato leaf', 'Tomato Leaf'), ('bamboo', 'Bamboo'), ('shiso', 'Shiso'), ('verbena', 'Verbena'), ('lemongrass', 'Lemongrass'), ('sea salt', 'Sea Salt'), ('marine breeze', 'Marine Breeze'), ('ozone', 'Ozone'), ('aquatic notes', 'Aquatic Notes'), ('peppermint', 'Peppermint'), ('mint', 'Mint'), ('basil', 'Basil'), ('rosemary', 'Rosemary'), ('thyme', 'Thyme'), ('tarragon', 'Tarragon'), ('clary sage', 'Clary Sage'), ('eucalyptus', 'Eucalyptus'), ('juniper berry', 'Juniper Berry'), ('ginger', 'Ginger'), ('pink pepper', 'Pink Pepper'), ('black pepper', 'Black Pepper'), ('cardamom', 'Cardamom'), ('coriander', 'Coriander'), ('anise', 'Anise'), ('fennel', 'Fennel'), ('green apple', 'Green Apple'), ('pear', 'Pear'), ('pineapple', 'Pineapple'), ('melon', 'Melon'), ('watermelon', 'Watermelon'), ('lychee', 'Lychee'), ('white grape', 'White Grape'), ('kiwi', 'Kiwi'), ('aldehydes', 'Aldehydes')], max_length=100)),
                ('perfume_heart', models.CharField(choices=[('rose', 'Rose'), ('jasmine', 'Jasmine'), ('orange blossom', 'Orange Blossom'), ('neroli', 'Neroli'), ('peony', 'Peony'), ('magnolia', 'Magnolia'), ('lily of the valley', 'Lily Of The Valley'), ('freesia', 'Freesia'), ('ylang-ylang', 'Ylang Ylang'), ('tuberose', 'Tuberose'), ('gardenia', 'Gardenia'), ('osmanthus', 'Osmanthus'), ('violet', 'Violet'), ('iris', 'Iris Flower'), ('lotus', 'Lotus'), ('lily', 'Lily'), ('lavender', 'Lavender'), ('geranium', 'Geranium'), ('lilac', 'Lilac'), ('mimosa', 'Mimosa'), ('hyacinth', 'Hyacinth'), ('peach', 'Peach'), ('apricot', 'Apricot'), ('plum', 'Plum'), ('sour cherry', 'Sour Cherry'), ('sweet cherry', 'Sweet Cherry'), ('raspberry', 'Raspberry'), ('strawberry', 'Strawberry'), ('blackberry', 'Blackberry'), ('blueberry', 'Blueberry'), ('pomegranate', 'Pomegranate'), ('fig', 'Fig'), ('mango', 'Mango'), ('passion fruit', 'Passion Fruit'), ('coconut', 'Coconut'), ('lychee', 'Lychee'), ('black tea', 'Black Tea'), ('green tea', 'Green Tea'), ('mate', 'Mate'), ('chamomile', 'Chamomile'), ('cinnamon', 'Cinnamon'), ('clove', 'Clove'), ('nutmeg', 'Nutmeg'), ('caraway', 'Caraway'), ('candied ginger', 'Candied Ginger'), ('honey', 'Honey'), ('floral honey', 'Floral Honey'), ('powdery note', 'Powdery Note'), ('rhubarb', 'Rhubarb'), ('elderflower', 'Elderflower')], max_length=100)),
                ('last_notes', models.CharField(choices=[('cedar', 'Cedar'), ('sandalwood', 'Sandalwood'), ('patchouli', 'Patchouli'), ('vetiver', 'Vetiver'), ('guaiac wood', 'Guaiac Wood'), ('oud', 'Oud'), ('agarwood', 'Agarwood'), ('oak', 'Oak'), ('teak', 'Teak'), ('rosewood', 'Rosewood'), ('amyris', 'Amyris'), ('cashmeran', 'Cashmeran'), ('Iso E Super', 'Iso E Super'), ('amberwood', 'Amberwood'), ('labdanum', 'Labdanum'), ('benzoin', 'Benzoin'), ('opoponax', 'Opoponax'), ('myrrh', 'Myrrh'), ('frankincense', 'Frankincense'), ('peru balsam', 'Peru Balsam'), ('tolu balsam', 'Tolu Balsam'), ('amber', 'Amber'), ('ambroxan', 'Ambroxan'), ('ambergris', 'Ambergris'), ('white musk', 'White Musk'), ('musk', 'Musk'), ('vanilla', 'Vanilla'), ('tonka bean', 'Tonka Bean'), ('cocoa', 'Cocoa'), ('chocolate', 'Chocolate'), ('coffee', 'Coffee'), ('praline', 'Praline'), ('caramel', 'Caramel'), ('orris butter', 'Orris Butter'), ('orris powder', 'Orris Powder'), ('marshmallow', 'Marshmallow'), ('sugar', 'Sugar'), ('toffee', 'Toffee'), ('tobacco', 'Tobacco'), ('tobacco leaf', 'Tobacco Leaf'), ('oakmoss', 'Oakmoss'), ('leather', 'Leather'), ('suede', 'Suede'), ('birch tar', 'Birch Tar'), ('hay', 'Hay'), ('smoke', 'Smoke'), ('resinous smoke', 'Resinous Smoke'), ('nutty chocolate accord', 'Nutty Chocolate Accord')], max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=100)),
            ],
            options={
                'db_table': 'perfumes',
            },
        ),
    ]
