# Generated by Django 5.2.7 on 2025-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='currency',
            field=models.CharField(choices=[('uah', 'Uah'), ('usd', 'Usd')], max_length=10),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='volume',
            field=models.CharField(choices=[('10', 'Ml 10'), ('20', 'Ml 20'), ('30', 'Ml 30'), ('50', 'Ml 50'), ('75', 'Ml 75'), ('100', 'Ml 100')], max_length=100),
        ),
    ]
