# Generated by Django 5.2.7 on 2025-11-03 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('uah', 'Uah'), ('usd', 'Usd')], max_length=10)),
                ('available', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField()),
                ('first_notes', models.CharField(max_length=255)),
                ('perfume_heart', models.CharField(max_length=255)),
                ('last_notes', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'perfumes',
                'managed': False,
            },
        ),
    ]
