# Generated by Django 5.2.7 on 2025-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_perfume_sex_alter_perfume_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfume',
        ),
    ]
