# Generated by Django 5.2.7 on 2025-11-10 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('nova', 'Nova'), ('ukr', 'Ukr'), ('meest', 'Meest')], max_length=20)),
                ('prefix', models.CharField(choices=[('nova', 'Nova'), ('ukr', 'Ukr'), ('meest', 'Meest')], max_length=20)),
            ],
            options={
                'db_table': 'delivery_companies',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting acceptance', 'Awaiting Acceptance'), ('awaiting shipment', 'Awaiting Shipment'), ('in transit', 'In Transit'), ('arrived', 'Arrived'), ('accepted', 'Accepted'), ('success', 'Success'), ('returned', 'Returned'), ('deleted', 'Deleted')], default='awaiting acceptance', max_length=50)),
                ('payment', models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online')], default='cod', max_length=20)),
                ('price', models.IntegerField()),
                ('delivery_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.deliverycompany')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('weight', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
