# Generated by Django 5.2.7 on 2025-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cod', 'Cod'), ('online', 'Online')], default='cod', max_length=20),
        ),
    ]
