# Generated by Django 5.2.7 on 2025-11-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_company',
            new_name='deliveryCompany',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_id',
            new_name='deliveryId',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='itemPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='totalPrice',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_weight',
            new_name='totalWeight',
        ),
    ]
