# Generated by Django 5.2.7 on 2025-11-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_created_at_order_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryCompany',
            new_name='deliveryCompanyId',
        ),
    ]
