# Generated by Django 5.2.7 on 2025-11-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_deliverycompany_order_deliverycompanyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderId',
        ),
    ]
