# Generated by Django 5.2.7 on 2025-11-10 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_price', models.IntegerField()),
                ('ttn', models.BigIntegerField()),
                ('new_address', models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=5)),
                ('payer_type', models.CharField(choices=[('Sender', 'Sender'), ('Recipient', 'Recipient')], default='Recipient', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('NonCash', 'Non-Cash')], default='Cash', max_length=20)),
                ('cargo_type', models.CharField(choices=[('Cargo', 'Cargo'), ('Parcel', 'Parcel'), ('Documents', 'Documents')], default='Parcel', max_length=20)),
                ('weight', models.FloatField()),
                ('service_type', models.CharField(choices=[('WarehouseWarehouse', 'Warehouse → Warehouse'), ('WarehouseDoors', 'Warehouse → Doors'), ('DoorsWarehouse', 'Doors → Warehouse'), ('DoorsDoors', 'Doors → Doors')], default='WarehouseWarehouse', max_length=30)),
                ('seats_amount', models.CharField(default='1', max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('city_sender', models.UUIDField()),
                ('sender', models.UUIDField()),
                ('sender_address', models.UUIDField()),
                ('contact_sender', models.UUIDField()),
                ('sender_phone', models.CharField(max_length=60)),
                ('city_recipient', models.UUIDField()),
                ('recipient', models.UUIDField()),
                ('recipient_address', models.UUIDField()),
                ('contact_recipient', models.UUIDField()),
                ('recipient_phone', models.CharField(max_length=60)),
                ('cargo_type_backward', models.CharField(default='Money', max_length=100)),
                ('redelivery_string', models.IntegerField()),
                ('recipient_bank_card', models.CharField(max_length=100)),
                ('recipient_first_name', models.CharField(max_length=100)),
                ('recipient_last_name', models.CharField(max_length=100)),
                ('cost_redelivery', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nova_orders', to='order.deliverycompany')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nova_orders', to='order.order')),
            ],
            options={
                'db_table': 'nova_orders',
            },
        ),
    ]
