# Generated by Django 5.2.7 on 2025-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaorder',
            name='new_address',
            field=models.CharField(choices=[('0', 'Zero'), ('1', 'One')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='novaorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('NonCash', 'Non Cash')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='novaorder',
            name='service_type',
            field=models.CharField(choices=[('WarehouseWarehouse', 'Warehouse Warehouse'), ('WarehouseDoors', 'Warehouse Doors'), ('DoorsWarehouse', 'Doors Warehouse'), ('DoorsDoors', 'Doors Doors')], default='WarehouseWarehouse', max_length=30),
        ),
    ]
