# Generated by Django 5.2.7 on 2025-11-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_rename_cargo_type_novaorder_cargotype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novaorder',
            old_name='order',
            new_name='orderId',
        ),
    ]
